//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGMEBackend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InternalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PGMEBackend.InternalStrings", typeof(InternalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked downwards.
        /// </summary>
        internal static string BehaviorByteBlockedDown {
            get {
                return ResourceManager.GetString("BehaviorByteBlockedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked leftwards.
        /// </summary>
        internal static string BehaviorByteBlockedLeft {
            get {
                return ResourceManager.GetString("BehaviorByteBlockedLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked rightwards.
        /// </summary>
        internal static string BehaviorByteBlockedRight {
            get {
                return ResourceManager.GetString("BehaviorByteBlockedRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked upwards.
        /// </summary>
        internal static string BehaviorByteBlockedUp {
            get {
                return ResourceManager.GetString("BehaviorByteBlockedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprints script.
        /// </summary>
        internal static string BehaviorByteBlueprints {
            get {
                return ResourceManager.GetString("BehaviorByteBlueprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookshelf script.
        /// </summary>
        internal static string BehaviorByteBookshelf {
            get {
                return ResourceManager.GetString("BehaviorByteBookshelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee cup near computer script.
        /// </summary>
        internal static string BehaviorByteCoffee {
            get {
                return ResourceManager.GetString("BehaviorByteCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-usable computer script.
        /// </summary>
        internal static string BehaviorByteComputer {
            get {
                return ResourceManager.GetString("BehaviorByteComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cracked ice.
        /// </summary>
        internal static string BehaviorByteCrackedIce {
            get {
                return ResourceManager.GetString("BehaviorByteCrackedIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster script.
        /// </summary>
        internal static string BehaviorByteCutePoster {
            get {
                return ResourceManager.GetString("BehaviorByteCutePoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride bike down (Cycling Road).
        /// </summary>
        internal static string BehaviorByteCycle {
            get {
                return ResourceManager.GetString("BehaviorByteCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish cabinet script.
        /// </summary>
        internal static string BehaviorByteDishCabinet {
            get {
                return ResourceManager.GetString("BehaviorByteDishCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dresser script.
        /// </summary>
        internal static string BehaviorByteDresser {
            get {
                return ResourceManager.GetString("BehaviorByteDresser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast moving current script.
        /// </summary>
        internal static string BehaviorByteFastCurrent {
            get {
                return ResourceManager.GetString("BehaviorByteFastCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footprints.
        /// </summary>
        internal static string BehaviorByteFootprints {
            get {
                return ResourceManager.GetString("BehaviorByteFootprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragile ice.
        /// </summary>
        internal static string BehaviorByteFragileIce {
            get {
                return ResourceManager.GetString("BehaviorByteFragileIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall grass animation.
        /// </summary>
        internal static string BehaviorByteGrassAnim {
            get {
                return ResourceManager.GetString("BehaviorByteGrassAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfway underwater.
        /// </summary>
        internal static string BehaviorByteHalfUnderwater {
            get {
                return ResourceManager.GetString("BehaviorByteHalfUnderwater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice sliding.
        /// </summary>
        internal static string BehaviorByteIceSliding {
            get {
                return ResourceManager.GetString("BehaviorByteIceSliding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo Plateau (ultimate goal).
        /// </summary>
        internal static string BehaviorByteIndigo1 {
            get {
                return ResourceManager.GetString("BehaviorByteIndigo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo Plateau (highest authority).
        /// </summary>
        internal static string BehaviorByteIndigo2 {
            get {
                return ResourceManager.GetString("BehaviorByteIndigo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump down over block.
        /// </summary>
        internal static string BehaviorByteJumpDown {
            get {
                return ResourceManager.GetString("BehaviorByteJumpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump left over block.
        /// </summary>
        internal static string BehaviorByteJumpLeft {
            get {
                return ResourceManager.GetString("BehaviorByteJumpLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump right over block.
        /// </summary>
        internal static string BehaviorByteJumpRight {
            get {
                return ResourceManager.GetString("BehaviorByteJumpRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump up over block.
        /// </summary>
        internal static string BehaviorByteJumpUp {
            get {
                return ResourceManager.GetString("BehaviorByteJumpUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blinkenlights script.
        /// </summary>
        internal static string BehaviorByteLights {
            get {
                return ResourceManager.GetString("BehaviorByteLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machinery script.
        /// </summary>
        internal static string BehaviorByteMachinery {
            get {
                return ResourceManager.GetString("BehaviorByteMachinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string BehaviorByteNone {
            get {
                return ResourceManager.GetString("BehaviorByteNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC script.
        /// </summary>
        internal static string BehaviorBytePC {
            get {
                return ResourceManager.GetString("BehaviorBytePC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon Center sign script.
        /// </summary>
        internal static string BehaviorBytePkmnCenter {
            get {
                return ResourceManager.GetString("BehaviorBytePkmnCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon Mart sign script.
        /// </summary>
        internal static string BehaviorBytePkmnMart {
            get {
                return ResourceManager.GetString("BehaviorBytePkmnMart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrigerator script.
        /// </summary>
        internal static string BehaviorByteRefrigerator {
            get {
                return ResourceManager.GetString("BehaviorByteRefrigerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signpost (sign without A).
        /// </summary>
        internal static string BehaviorByteSignpost {
            get {
                return ResourceManager.GetString("BehaviorByteSignpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sink script.
        /// </summary>
        internal static string BehaviorByteSink {
            get {
                return ResourceManager.GetString("BehaviorByteSink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin pad down.
        /// </summary>
        internal static string BehaviorByteSpinDown {
            get {
                return ResourceManager.GetString("BehaviorByteSpinDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin pad left.
        /// </summary>
        internal static string BehaviorByteSpinLeft {
            get {
                return ResourceManager.GetString("BehaviorByteSpinLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin pad right.
        /// </summary>
        internal static string BehaviorByteSpinRight {
            get {
                return ResourceManager.GetString("BehaviorByteSpinRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin pad up.
        /// </summary>
        internal static string BehaviorByteSpinUp {
            get {
                return ResourceManager.GetString("BehaviorByteSpinUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop spinning.
        /// </summary>
        internal static string BehaviorByteStopSpinning {
            get {
                return ResourceManager.GetString("BehaviorByteStopSpinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV script.
        /// </summary>
        internal static string BehaviorByteTV {
            get {
                return ResourceManager.GetString("BehaviorByteTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vase script.
        /// </summary>
        internal static string BehaviorByteVase {
            get {
                return ResourceManager.GetString("BehaviorByteVase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, arrow down.
        /// </summary>
        internal static string BehaviorByteWarpArrowDown {
            get {
                return ResourceManager.GetString("BehaviorByteWarpArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, arrow left.
        /// </summary>
        internal static string BehaviorByteWarpArrowLeft {
            get {
                return ResourceManager.GetString("BehaviorByteWarpArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, arrow right.
        /// </summary>
        internal static string BehaviorByteWarpArrowRight {
            get {
                return ResourceManager.GetString("BehaviorByteWarpArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, arrow up.
        /// </summary>
        internal static string BehaviorByteWarpArrowUp {
            get {
                return ResourceManager.GetString("BehaviorByteWarpArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, cave entrance.
        /// </summary>
        internal static string BehaviorByteWarpCave {
            get {
                return ResourceManager.GetString("BehaviorByteWarpCave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, door animation.
        /// </summary>
        internal static string BehaviorByteWarpDoor {
            get {
                return ResourceManager.GetString("BehaviorByteWarpDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, escalator down.
        /// </summary>
        internal static string BehaviorByteWarpEscalatorDown {
            get {
                return ResourceManager.GetString("BehaviorByteWarpEscalatorDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, escalator up.
        /// </summary>
        internal static string BehaviorByteWarpEscalatorUp {
            get {
                return ResourceManager.GetString("BehaviorByteWarpEscalatorUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, falling in hole.
        /// </summary>
        internal static string BehaviorByteWarpHole {
            get {
                return ResourceManager.GetString("BehaviorByteWarpHole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, ladder.
        /// </summary>
        internal static string BehaviorByteWarpLadder {
            get {
                return ResourceManager.GetString("BehaviorByteWarpLadder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, stairs down + left.
        /// </summary>
        internal static string BehaviorByteWarpStairsDownLeft {
            get {
                return ResourceManager.GetString("BehaviorByteWarpStairsDownLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, stairs down + right.
        /// </summary>
        internal static string BehaviorByteWarpStairsDownRight {
            get {
                return ResourceManager.GetString("BehaviorByteWarpStairsDownRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, stairs up + left.
        /// </summary>
        internal static string BehaviorByteWarpStairsUpLeft {
            get {
                return ResourceManager.GetString("BehaviorByteWarpStairsUpLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, stairs up + right.
        /// </summary>
        internal static string BehaviorByteWarpStairsUpRight {
            get {
                return ResourceManager.GetString("BehaviorByteWarpStairsUpRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp, using teleporter.
        /// </summary>
        internal static string BehaviorByteWarpTeleport {
            get {
                return ResourceManager.GetString("BehaviorByteWarpTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string BehaviorByteWindow1 {
            get {
                return ResourceManager.GetString("BehaviorByteWindow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window type 2.
        /// </summary>
        internal static string BehaviorByteWindow2 {
            get {
                return ResourceManager.GetString("BehaviorByteWindow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World map script.
        /// </summary>
        internal static string BehaviorByteWorldMap {
            get {
                return ResourceManager.GetString("BehaviorByteWorldMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear List.
        /// </summary>
        internal static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0} map layout(s)..
        /// </summary>
        internal static string CouldNotFindLayout {
            get {
                return ResourceManager.GetString("CouldNotFindLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Find Map Layouts.
        /// </summary>
        internal static string CouldNotFindLayoutTitle {
            get {
                return ResourceManager.GetString("CouldNotFindLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read {0} tileset from layout {1}.
        ///Attempted to read tileset from offset: {2}..
        /// </summary>
        internal static string CouldNotReadTileset {
            get {
                return ResourceManager.GetString("CouldNotReadTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tileset Error.
        /// </summary>
        internal static string CouldNotReadTilesetTitle {
            get {
                return ResourceManager.GetString("CouldNotReadTilesetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this entity?.
        /// </summary>
        internal static string DeleteEntity {
            get {
                return ResourceManager.GetString("DeleteEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteEntityTitle {
            get {
                return ResourceManager.GetString("DeleteEntityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string FileNotFoundTitle {
            get {
                return ResourceManager.GetString("FileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global.
        /// </summary>
        internal static string GlobalTileset {
            get {
                return ResourceManager.GetString("GlobalTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Layout.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string LocalTileset {
            get {
                return ResourceManager.GetString("LocalTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map {0} loaded in {1} seconds..
        /// </summary>
        internal static string MapLoadedStatus {
            get {
                return ResourceManager.GetString("MapLoadedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple entities selected..
        /// </summary>
        internal static string MultipleEntitiesSelected {
            get {
                return ResourceManager.GetString("MultipleEntitiesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no entities of this type available on this map..
        /// </summary>
        internal static string NoEntitiesOfThisType {
            get {
                return ResourceManager.GetString("NoEntitiesOfThisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not yet chosen a script editor.
        ///Would you like to go to the Settings dialog and choose an editor?.
        /// </summary>
        internal static string NoScriptEditorSpecified {
            get {
                return ResourceManager.GetString("NoScriptEditorSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Script Editor Chosen.
        /// </summary>
        internal static string NoScriptEditorSpecifiedTitle {
            get {
                return ResourceManager.GetString("NoScriptEditorSpecifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; cannot be opened. Do you want to remove the reference to it from the Recent Files list?.
        /// </summary>
        internal static string RecentFileNotFound {
            get {
                return ResourceManager.GetString("RecentFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program will need to be restarted to apply the new language preference..
        /// </summary>
        internal static string RestartToSaveLanguage {
            get {
                return ResourceManager.GetString("RestartToSaveLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string RestartToSaveLanguageTitle {
            get {
                return ResourceManager.GetString("RestartToSaveLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM type {0} is not recognized..
        /// </summary>
        internal static string ROMCodeNotFound {
            get {
                return ResourceManager.GetString("ROMCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized ROM.
        /// </summary>
        internal static string ROMCodeNotFoundTitle {
            get {
                return ResourceManager.GetString("ROMCodeNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM {0} loaded in {1} seconds..
        /// </summary>
        internal static string ROMLoadedStatus {
            get {
                return ResourceManager.GetString("ROMLoadedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read config file.
        /// </summary>
        internal static string UnableToReadConfig {
            get {
                return ResourceManager.GetString("UnableToReadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Read Config.
        /// </summary>
        internal static string UnableToReadConfigTitle {
            get {
                return ResourceManager.GetString("UnableToReadConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Index.
        /// </summary>
        internal static string UnknownIndex {
            get {
                return ResourceManager.GetString("UnknownIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Song.
        /// </summary>
        internal static string UnknownSong {
            get {
                return ResourceManager.GetString("UnknownSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are changes that haven&apos;t been saved.
        ///Save changes before continuing?.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are changes that haven&apos;t been saved.
        ///Save changes before exiting?.
        /// </summary>
        internal static string UnsavedChangesExit {
            get {
                return ResourceManager.GetString("UnsavedChangesExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        internal static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }
    }
}
