//------------------------------------------------------------------------------
// <auto-generated>
//     Työkalu muodosti tämän koodin.
//     Suorituksenaikainen versio:2.0.50727.4200
//
//     Tähän tiedostoon tehdyt muutokset saattavat aiheuttaa virheellistä toimintaa. Ne menetetään, jos
//     koodi muodostetaan uudelleen.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

namespace SappyXMLEditor
{

    /// <huomautukset/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class sappy
    {

        private rom[] romField;

        /// <huomautukset/>
        [System.Xml.Serialization.XmlElementAttribute("rom")]
        public rom[] rom
        {
            get
            {
                return this.romField;
            }
            set
            {
                this.romField = value;
            }
        }
    }

    /// <huomautukset/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class rom
    {

        private playlist[] playlistField;

        private midimap midimapField;

        private string codeField;

        private string creatorField;

        private string nameField;

        private string screenshotField;

        private string songtableField;

        private string taggerField;

        /// <huomautukset/>
        [System.Xml.Serialization.XmlElementAttribute("playlist")]
        public playlist[] playlist
        {
            get
            {
                return this.playlistField;
            }
            set
            {
                this.playlistField = value;
            }
        }

        /// <huomautukset/>
        public midimap midimap
        {
            get
            {
                return this.midimapField;
            }
            set
            {
                this.midimapField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NCName")]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string creator
        {
            get
            {
                return this.creatorField;
            }
            set
            {
                this.creatorField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NCName")]
        public string screenshot
        {
            get
            {
                return this.screenshotField;
            }
            set
            {
                this.screenshotField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string songtable
        {
            get
            {
                return this.songtableField;
            }
            set
            {
                this.songtableField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tagger
        {
            get
            {
                return this.taggerField;
            }
            set
            {
                this.taggerField = value;
            }
        }
    }

    /// <huomautukset/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class playlist
    {

        private song[] songField;

        private string nameField;

        private string stealField;

        /// <huomautukset/>
        [System.Xml.Serialization.XmlElementAttribute("song")]
        public song[] song
        {
            get
            {
                return this.songField;
            }
            set
            {
                this.songField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NCName")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NCName")]
        public string steal
        {
            get
            {
                return this.stealField;
            }
            set
            {
                this.stealField = value;
            }
        }
    }

    /// <huomautukset/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class song
    {

        private string trackField;

        private string[] textField;

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string track
        {
            get
            {
                return this.trackField;
            }
            set
            {
                this.trackField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <huomautukset/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class midimap
    {

        private inst instField;

        private drum[] drumField;

        /// <huomautukset/>
        public inst inst
        {
            get
            {
                return this.instField;
            }
            set
            {
                this.instField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlElementAttribute("drum")]
        public drum[] drum
        {
            get
            {
                return this.drumField;
            }
            set
            {
                this.drumField = value;
            }
        }
    }

    /// <huomautukset/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class inst
    {

        private string fromField;

        private string toField;

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }

    /// <huomautukset/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class drum
    {

        private string fromField;

        private string kitField;

        private string toField;

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string kit
        {
            get
            {
                return this.kitField;
            }
            set
            {
                this.kitField = value;
            }
        }

        /// <huomautukset/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }
}